version: '3.8'
services:
  postgres:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=sefyu
      - POSTGRES_PASSWORD=soufa
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
volumes:
  postgres: # volume name
